# This is a basic workflow to help you get started with Actions

name: CI-Test2

# Controls when the workflow will run
on:
 issue_comment:
    types: [created, edited, deleted]

jobs:
  vars-read:
    if: contains(github.event.comment.body, 'ok!')
    runs-on: ubuntu-latess
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Read file content
        run: | 
          test1=`ls -ltr /home/runner/work/GitAction-Test/GitAction-Test/ | tail -1 | awk '{print $9}'`
          echo $test1
        
