# This is a basic workflow to help you get started with Actions

name: CI-Test1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "**/info.txt" ]

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Read file content
        run: | 
          test1=`ls -ltr /home/runner/work/GitAction-Test/GitAction-Test/ | tail -1 | awk '{print $9}'`
          cat /home/runner/work/GitAction-Test/GitAction-Test/$test1
        
