# This is a basic workflow to help you get started with Actions

name: CI-Test1

# Controls when the workflow will run
on:
 create:

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Read file content
        run: |
          echo "export TEST1=$(pwd)" >> $GITHUB_ENV
      
      - name: Show Test1 Directory
        run: |
          echo "Test1 directory path: $TEST1"
